// <auto-generated />
using System;
using Galenort.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Galenort.Infraestructura.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200722205623_migration2207correccion")]
    partial class migration2207correccion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Galenort.Dominio.Entidades.Dia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<short>("EstaEliminado");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("Dias");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Descripcion = "LUNES",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 2L,
                            Descripcion = "MARTES",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 3L,
                            Descripcion = "MIERCOLES",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 4L,
                            Descripcion = "JUEVES",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 5L,
                            Descripcion = "VIERNES",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 6L,
                            Descripcion = "LUNES A VIERNES",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 7L,
                            Descripcion = "SABADO",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 8L,
                            Descripcion = "Sujeto a acuerdo previo con el especialista",
                            EstaEliminado = (short)0
                        });
                });

            modelBuilder.Entity("Galenort.Dominio.Entidades.DiaHorario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<short>("EstaEliminado");

                    b.Property<long>("IdDia");

                    b.Property<long>("IdHorarioPrestador");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("IdDia");

                    b.HasIndex("IdHorarioPrestador");

                    b.ToTable("DiaHorarios");
                });

            modelBuilder.Entity("Galenort.Dominio.Entidades.Especialidad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<short>("EstaEliminado");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("Especialidades");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Descripcion = "FLEBOLOGIA",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 2L,
                            Descripcion = "ENDOCRINOLOGIA",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 3L,
                            Descripcion = "ECOGRAFIA",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 4L,
                            Descripcion = "NEUROLOGIA",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 5L,
                            Descripcion = "CLINICO",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 6L,
                            Descripcion = "DERMATOLOGIA",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 7L,
                            Descripcion = "GINECOLOGIA",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 8L,
                            Descripcion = "TRAUMATOLOGIA",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 9L,
                            Descripcion = "CIRUGIA GRAL",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 10L,
                            Descripcion = "PROCTOLOGIA",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 11L,
                            Descripcion = "CARDIOLOGIA",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 12L,
                            Descripcion = "NEUMONOLOGIA",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 13L,
                            Descripcion = "UROLOGIA",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 14L,
                            Descripcion = "PSICOLOGIA",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 15L,
                            Descripcion = "GASTROENTEROLOGIA",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 16L,
                            Descripcion = "CIRUGIA CARDIOVASCULAR",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 17L,
                            Descripcion = "PEDIATRIA",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 18L,
                            Descripcion = "ODONTOLOGIA",
                            EstaEliminado = (short)0
                        });
                });

            modelBuilder.Entity("Galenort.Dominio.Entidades.Establecimiento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<short>("EstaEliminado");

                    b.Property<long>("IdLocalidad");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("IdLocalidad");

                    b.ToTable("Establecimientos");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Direccion = "Avenida Belgrano 2970",
                            EstaEliminado = (short)0,
                            IdLocalidad = 1L,
                            RazonSocial = "Sanatorio Galeno S.C.E.I"
                        },
                        new
                        {
                            Id = 2L,
                            Direccion = "Jujuy 111",
                            EstaEliminado = (short)0,
                            IdLocalidad = 1L,
                            RazonSocial = "Sanatorio C.I.M.S.A"
                        },
                        new
                        {
                            Id = 3L,
                            Direccion = "Avenida Mitre 268",
                            EstaEliminado = (short)0,
                            IdLocalidad = 1L,
                            RazonSocial = "Sanatorio Central S.R.L"
                        },
                        new
                        {
                            Id = 4L,
                            Direccion = "Avenida Mitre 263",
                            EstaEliminado = (short)0,
                            IdLocalidad = 2L,
                            RazonSocial = "Sanatorio Mitre S.R.L"
                        });
                });

            modelBuilder.Entity("Galenort.Dominio.Entidades.HorarioPrestador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<short>("EstaEliminado");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("Time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("Time");

                    b.Property<long>("IdPrestadorEstablecimiento");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("IdPrestadorEstablecimiento");

                    b.ToTable("HorarioPrestadores");
                });

            modelBuilder.Entity("Galenort.Dominio.Entidades.Localidad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<short>("EstaEliminado");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("Localidades");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Descripcion = "San Miguel de Tucumán",
                            EstaEliminado = (short)0
                        },
                        new
                        {
                            Id = 2L,
                            Descripcion = "Aguilares",
                            EstaEliminado = (short)0
                        });
                });

            modelBuilder.Entity("Galenort.Dominio.Entidades.Prestador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<short>("EstaEliminado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("Prestadores");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Apellido = "Agüero Avila",
                            EstaEliminado = (short)0,
                            Nombre = "Marcelo"
                        },
                        new
                        {
                            Id = 2L,
                            Apellido = "Escodamaglia",
                            EstaEliminado = (short)0,
                            Nombre = "Sergio"
                        },
                        new
                        {
                            Id = 3L,
                            Apellido = "Chavez",
                            EstaEliminado = (short)0,
                            Nombre = "Nilda"
                        },
                        new
                        {
                            Id = 4L,
                            Apellido = "Cabral",
                            EstaEliminado = (short)0,
                            Nombre = "Clelia"
                        },
                        new
                        {
                            Id = 5L,
                            Apellido = "Benaglio",
                            EstaEliminado = (short)0,
                            Nombre = "Horacio"
                        },
                        new
                        {
                            Id = 6L,
                            Apellido = "Gimenez",
                            EstaEliminado = (short)0,
                            Nombre = "Nazareno"
                        },
                        new
                        {
                            Id = 7L,
                            Apellido = "Venturini",
                            EstaEliminado = (short)0,
                            Nombre = "Arturo"
                        },
                        new
                        {
                            Id = 8L,
                            Apellido = "Baza",
                            EstaEliminado = (short)0,
                            Nombre = "David"
                        },
                        new
                        {
                            Id = 9L,
                            Apellido = "Frau",
                            EstaEliminado = (short)0,
                            Nombre = "Daniel"
                        },
                        new
                        {
                            Id = 10L,
                            Apellido = "Argañaraz",
                            EstaEliminado = (short)0,
                            Nombre = "Carmen"
                        },
                        new
                        {
                            Id = 11L,
                            Apellido = "Valde lico",
                            EstaEliminado = (short)0,
                            Nombre = "Guillermo"
                        },
                        new
                        {
                            Id = 12L,
                            Apellido = "Fernandez",
                            EstaEliminado = (short)0,
                            Nombre = "Silvio"
                        },
                        new
                        {
                            Id = 13L,
                            Apellido = "Quiroga",
                            EstaEliminado = (short)0,
                            Nombre = "Adrian"
                        },
                        new
                        {
                            Id = 14L,
                            Apellido = "Juarez",
                            EstaEliminado = (short)0,
                            Nombre = "Pablo"
                        },
                        new
                        {
                            Id = 15L,
                            Apellido = "Figueroa",
                            EstaEliminado = (short)0,
                            Nombre = "Ricardo"
                        },
                        new
                        {
                            Id = 16L,
                            Apellido = "Lazarte",
                            EstaEliminado = (short)0,
                            Nombre = "Jorge"
                        },
                        new
                        {
                            Id = 17L,
                            Apellido = "Gerez",
                            EstaEliminado = (short)0,
                            Nombre = "Liliana"
                        },
                        new
                        {
                            Id = 18L,
                            Apellido = "Neme",
                            EstaEliminado = (short)0,
                            Nombre = "Graciela"
                        },
                        new
                        {
                            Id = 19L,
                            Apellido = "Tobias Teruel",
                            EstaEliminado = (short)0,
                            Nombre = "Oscar"
                        },
                        new
                        {
                            Id = 20L,
                            Apellido = "Lopez",
                            EstaEliminado = (short)0,
                            Nombre = "Lorena"
                        },
                        new
                        {
                            Id = 21L,
                            Apellido = "Perpignal",
                            EstaEliminado = (short)0,
                            Nombre = "Luisa"
                        },
                        new
                        {
                            Id = 22L,
                            Apellido = "Silva",
                            EstaEliminado = (short)0,
                            Nombre = "Enzo"
                        },
                        new
                        {
                            Id = 23L,
                            Apellido = "Mena",
                            EstaEliminado = (short)0,
                            Nombre = "Vicente"
                        },
                        new
                        {
                            Id = 24L,
                            Apellido = "Canseco",
                            EstaEliminado = (short)0,
                            Nombre = "Ricardo"
                        },
                        new
                        {
                            Id = 25L,
                            Apellido = "Gómez",
                            EstaEliminado = (short)0,
                            Nombre = "Sergio"
                        },
                        new
                        {
                            Id = 26L,
                            Apellido = "Mena",
                            EstaEliminado = (short)0,
                            Nombre = "Hernán"
                        },
                        new
                        {
                            Id = 27L,
                            Apellido = "Ramos",
                            EstaEliminado = (short)0,
                            Nombre = "Hernández"
                        },
                        new
                        {
                            Id = 28L,
                            Apellido = "Robles",
                            EstaEliminado = (short)0,
                            Nombre = "Chavez"
                        },
                        new
                        {
                            Id = 29L,
                            Apellido = "Nieto",
                            EstaEliminado = (short)0,
                            Nombre = "Silva"
                        },
                        new
                        {
                            Id = 30L,
                            Apellido = "Brodesen",
                            EstaEliminado = (short)0,
                            Nombre = "Liliana"
                        },
                        new
                        {
                            Id = 31L,
                            Apellido = "Jaime",
                            EstaEliminado = (short)0,
                            Nombre = "Sebastian"
                        },
                        new
                        {
                            Id = 32L,
                            Apellido = "Fernandez",
                            EstaEliminado = (short)0,
                            Nombre = "Gómez"
                        },
                        new
                        {
                            Id = 33L,
                            Apellido = "Erbetta",
                            EstaEliminado = (short)0,
                            Nombre = "Ruben Julio"
                        },
                        new
                        {
                            Id = 34L,
                            Apellido = "Andjel",
                            EstaEliminado = (short)0,
                            Nombre = "Germán Alejandro"
                        },
                        new
                        {
                            Id = 35L,
                            Apellido = "Saracho",
                            EstaEliminado = (short)0,
                            Nombre = "Victor Manuel"
                        },
                        new
                        {
                            Id = 36L,
                            Apellido = "Raskosky",
                            EstaEliminado = (short)0,
                            Nombre = "Luis Raul"
                        },
                        new
                        {
                            Id = 37L,
                            Apellido = "Azcárate Pacheres",
                            EstaEliminado = (short)0,
                            Nombre = "Aníbal"
                        },
                        new
                        {
                            Id = 38L,
                            Apellido = "Zelada",
                            EstaEliminado = (short)0,
                            Nombre = "Fernando"
                        },
                        new
                        {
                            Id = 39L,
                            Apellido = "Michel",
                            EstaEliminado = (short)0,
                            Nombre = "  Jhony"
                        },
                        new
                        {
                            Id = 40L,
                            Apellido = "Rojas",
                            EstaEliminado = (short)0,
                            Nombre = "Adrian"
                        },
                        new
                        {
                            Id = 41L,
                            Apellido = "Ruiz Diaz",
                            EstaEliminado = (short)0,
                            Nombre = "Hector"
                        },
                        new
                        {
                            Id = 42L,
                            Apellido = "Ale",
                            EstaEliminado = (short)0,
                            Nombre = "Pablo"
                        },
                        new
                        {
                            Id = 43L,
                            Apellido = "Ale Levin",
                            EstaEliminado = (short)0,
                            Nombre = "Walter"
                        },
                        new
                        {
                            Id = 44L,
                            Apellido = "Paz",
                            EstaEliminado = (short)0,
                            Nombre = "Claudio"
                        },
                        new
                        {
                            Id = 45L,
                            Apellido = "Brito",
                            EstaEliminado = (short)0,
                            Nombre = "Guillermo"
                        },
                        new
                        {
                            Id = 46L,
                            Apellido = "Martinez",
                            EstaEliminado = (short)0,
                            Nombre = "Fabian"
                        },
                        new
                        {
                            Id = 47L,
                            Apellido = "Triguero",
                            EstaEliminado = (short)0,
                            Nombre = "Felix"
                        },
                        new
                        {
                            Id = 48L,
                            Apellido = "Raya",
                            EstaEliminado = (short)0,
                            Nombre = "Jose"
                        },
                        new
                        {
                            Id = 49L,
                            Apellido = "Suarez",
                            EstaEliminado = (short)0,
                            Nombre = "Jorge"
                        },
                        new
                        {
                            Id = 50L,
                            Apellido = "Alonso",
                            EstaEliminado = (short)0,
                            Nombre = "Gustavo"
                        },
                        new
                        {
                            Id = 51L,
                            Apellido = "Campero",
                            EstaEliminado = (short)0,
                            Nombre = "Silvia Graciela"
                        },
                        new
                        {
                            Id = 52L,
                            Apellido = "Romaño",
                            EstaEliminado = (short)0,
                            Nombre = "Murga"
                        },
                        new
                        {
                            Id = 53L,
                            Apellido = "Juan Ramon",
                            EstaEliminado = (short)0,
                            Nombre = "Cecilia"
                        },
                        new
                        {
                            Id = 54L,
                            Apellido = "Rovarini",
                            EstaEliminado = (short)0,
                            Nombre = "Ana"
                        },
                        new
                        {
                            Id = 55L,
                            Apellido = "Chehade",
                            EstaEliminado = (short)0,
                            Nombre = "Wadi"
                        },
                        new
                        {
                            Id = 56L,
                            Apellido = "Almeida",
                            EstaEliminado = (short)0,
                            Nombre = "Maria"
                        },
                        new
                        {
                            Id = 57L,
                            Apellido = "Perez Ordoñes",
                            EstaEliminado = (short)0,
                            Nombre = "Veronica"
                        },
                        new
                        {
                            Id = 58L,
                            Apellido = "Alvarez",
                            EstaEliminado = (short)0,
                            Nombre = "Carlos"
                        },
                        new
                        {
                            Id = 59L,
                            Apellido = "Fernandez",
                            EstaEliminado = (short)0,
                            Nombre = "Alvaro"
                        },
                        new
                        {
                            Id = 60L,
                            Apellido = "Perez",
                            EstaEliminado = (short)0,
                            Nombre = "Mulki"
                        },
                        new
                        {
                            Id = 61L,
                            Apellido = "Martinez",
                            EstaEliminado = (short)0,
                            Nombre = "Javier"
                        },
                        new
                        {
                            Id = 62L,
                            Apellido = "Avellaneda",
                            EstaEliminado = (short)0,
                            Nombre = "Maria"
                        },
                        new
                        {
                            Id = 63L,
                            Apellido = "Fierro",
                            EstaEliminado = (short)0,
                            Nombre = "Jorge"
                        },
                        new
                        {
                            Id = 64L,
                            Apellido = "Ledesma",
                            EstaEliminado = (short)0,
                            Nombre = "Jesus Emiliano"
                        },
                        new
                        {
                            Id = 65L,
                            Apellido = "Fadel",
                            EstaEliminado = (short)0,
                            Nombre = "Julio"
                        });
                });

            modelBuilder.Entity("Galenort.Dominio.Entidades.PrestadorEspecialidad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<short>("EstaEliminado");

                    b.Property<long>("IdEspecialidad");

                    b.Property<long>("IdPrestador");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("IdEspecialidad");

                    b.HasIndex("IdPrestador");

                    b.ToTable("PrestadorEspecialidades");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 1L,
                            IdPrestador = 1L
                        },
                        new
                        {
                            Id = 2L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 1L,
                            IdPrestador = 2L
                        },
                        new
                        {
                            Id = 3L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 2L,
                            IdPrestador = 3L
                        },
                        new
                        {
                            Id = 4L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 2L,
                            IdPrestador = 4L
                        },
                        new
                        {
                            Id = 5L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 3L,
                            IdPrestador = 5L
                        },
                        new
                        {
                            Id = 6L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 4L,
                            IdPrestador = 6L
                        },
                        new
                        {
                            Id = 7L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 5L,
                            IdPrestador = 7L
                        },
                        new
                        {
                            Id = 8L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 6L,
                            IdPrestador = 8L
                        },
                        new
                        {
                            Id = 9L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 7L,
                            IdPrestador = 9L
                        },
                        new
                        {
                            Id = 10L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 7L,
                            IdPrestador = 10L
                        },
                        new
                        {
                            Id = 11L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 8L,
                            IdPrestador = 11L
                        },
                        new
                        {
                            Id = 12L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 8L,
                            IdPrestador = 12L
                        },
                        new
                        {
                            Id = 13L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 8L,
                            IdPrestador = 13L
                        },
                        new
                        {
                            Id = 14L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 8L,
                            IdPrestador = 14L
                        },
                        new
                        {
                            Id = 15L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 9L,
                            IdPrestador = 15L
                        },
                        new
                        {
                            Id = 16L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 9L,
                            IdPrestador = 16L
                        },
                        new
                        {
                            Id = 17L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 10L,
                            IdPrestador = 17L
                        },
                        new
                        {
                            Id = 18L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 11L,
                            IdPrestador = 18L
                        },
                        new
                        {
                            Id = 19L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 11L,
                            IdPrestador = 19L
                        },
                        new
                        {
                            Id = 20L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 11L,
                            IdPrestador = 20L
                        },
                        new
                        {
                            Id = 21L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 12L,
                            IdPrestador = 21L
                        },
                        new
                        {
                            Id = 22L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 13L,
                            IdPrestador = 22L
                        },
                        new
                        {
                            Id = 23L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 5L,
                            IdPrestador = 23L
                        },
                        new
                        {
                            Id = 24L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 14L,
                            IdPrestador = 24L
                        },
                        new
                        {
                            Id = 25L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 9L,
                            IdPrestador = 25L
                        },
                        new
                        {
                            Id = 26L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 9L,
                            IdPrestador = 26L
                        },
                        new
                        {
                            Id = 27L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 7L,
                            IdPrestador = 27L
                        },
                        new
                        {
                            Id = 28L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 7L,
                            IdPrestador = 28L
                        },
                        new
                        {
                            Id = 29L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 7L,
                            IdPrestador = 29L
                        },
                        new
                        {
                            Id = 30L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 15L,
                            IdPrestador = 30L
                        },
                        new
                        {
                            Id = 31L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 13L,
                            IdPrestador = 31L
                        },
                        new
                        {
                            Id = 32L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 13L,
                            IdPrestador = 32L
                        },
                        new
                        {
                            Id = 33L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 16L,
                            IdPrestador = 33L
                        },
                        new
                        {
                            Id = 34L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 4L,
                            IdPrestador = 34L
                        },
                        new
                        {
                            Id = 35L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 11L,
                            IdPrestador = 35L
                        },
                        new
                        {
                            Id = 36L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 9L,
                            IdPrestador = 36L
                        },
                        new
                        {
                            Id = 37L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 5L,
                            IdPrestador = 37L
                        },
                        new
                        {
                            Id = 38L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 3L,
                            IdPrestador = 38L
                        },
                        new
                        {
                            Id = 39L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 9L,
                            IdPrestador = 39L
                        },
                        new
                        {
                            Id = 40L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 9L,
                            IdPrestador = 40L
                        },
                        new
                        {
                            Id = 41L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 13L,
                            IdPrestador = 41L
                        },
                        new
                        {
                            Id = 42L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 8L,
                            IdPrestador = 42L
                        },
                        new
                        {
                            Id = 43L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 8L,
                            IdPrestador = 43L
                        },
                        new
                        {
                            Id = 44L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 8L,
                            IdPrestador = 44L
                        },
                        new
                        {
                            Id = 45L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 17L,
                            IdPrestador = 45L
                        },
                        new
                        {
                            Id = 46L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 11L,
                            IdPrestador = 46L
                        },
                        new
                        {
                            Id = 47L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 12L,
                            IdPrestador = 47L
                        },
                        new
                        {
                            Id = 48L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 11L,
                            IdPrestador = 48L
                        },
                        new
                        {
                            Id = 49L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 11L,
                            IdPrestador = 49L
                        },
                        new
                        {
                            Id = 50L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 12L,
                            IdPrestador = 50L
                        },
                        new
                        {
                            Id = 51L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 6L,
                            IdPrestador = 51L
                        },
                        new
                        {
                            Id = 52L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 15L,
                            IdPrestador = 52L
                        },
                        new
                        {
                            Id = 53L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 15L,
                            IdPrestador = 53L
                        },
                        new
                        {
                            Id = 54L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 12L,
                            IdPrestador = 54L
                        },
                        new
                        {
                            Id = 55L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 17L,
                            IdPrestador = 55L
                        },
                        new
                        {
                            Id = 56L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 17L,
                            IdPrestador = 56L
                        },
                        new
                        {
                            Id = 57L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 17L,
                            IdPrestador = 57L
                        },
                        new
                        {
                            Id = 58L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 16L,
                            IdPrestador = 58L
                        },
                        new
                        {
                            Id = 59L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 16L,
                            IdPrestador = 59L
                        },
                        new
                        {
                            Id = 60L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 18L,
                            IdPrestador = 60L
                        },
                        new
                        {
                            Id = 61L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 11L,
                            IdPrestador = 61L
                        },
                        new
                        {
                            Id = 62L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 17L,
                            IdPrestador = 62L
                        },
                        new
                        {
                            Id = 63L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 9L,
                            IdPrestador = 63L
                        },
                        new
                        {
                            Id = 64L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 11L,
                            IdPrestador = 64L
                        },
                        new
                        {
                            Id = 65L,
                            EstaEliminado = (short)0,
                            IdEspecialidad = 8L,
                            IdPrestador = 65L
                        });
                });

            modelBuilder.Entity("Galenort.Dominio.Entidades.PrestadorEstablecimiento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<short>("EstaEliminado");

                    b.Property<long>("IdEstablecimiento");

                    b.Property<long>("IdPrestadorEspecialidad");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("IdEstablecimiento");

                    b.HasIndex("IdPrestadorEspecialidad");

                    b.ToTable("PrestadorEstablecimientos");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 3L,
                            IdPrestadorEspecialidad = 1L
                        },
                        new
                        {
                            Id = 2L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 3L,
                            IdPrestadorEspecialidad = 2L
                        },
                        new
                        {
                            Id = 3L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 3L,
                            IdPrestadorEspecialidad = 3L
                        },
                        new
                        {
                            Id = 4L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 3L,
                            IdPrestadorEspecialidad = 4L
                        },
                        new
                        {
                            Id = 5L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 3L,
                            IdPrestadorEspecialidad = 5L
                        },
                        new
                        {
                            Id = 6L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 3L,
                            IdPrestadorEspecialidad = 6L
                        },
                        new
                        {
                            Id = 7L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 3L,
                            IdPrestadorEspecialidad = 7L
                        },
                        new
                        {
                            Id = 8L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 3L,
                            IdPrestadorEspecialidad = 8L
                        },
                        new
                        {
                            Id = 9L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 3L,
                            IdPrestadorEspecialidad = 9L
                        },
                        new
                        {
                            Id = 10L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 3L,
                            IdPrestadorEspecialidad = 10L
                        },
                        new
                        {
                            Id = 11L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 3L,
                            IdPrestadorEspecialidad = 11L
                        },
                        new
                        {
                            Id = 12L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 3L,
                            IdPrestadorEspecialidad = 12L
                        },
                        new
                        {
                            Id = 13L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 3L,
                            IdPrestadorEspecialidad = 13L
                        },
                        new
                        {
                            Id = 14L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 3L,
                            IdPrestadorEspecialidad = 14L
                        },
                        new
                        {
                            Id = 15L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 3L,
                            IdPrestadorEspecialidad = 15L
                        },
                        new
                        {
                            Id = 16L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 3L,
                            IdPrestadorEspecialidad = 16L
                        },
                        new
                        {
                            Id = 17L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 3L,
                            IdPrestadorEspecialidad = 17L
                        },
                        new
                        {
                            Id = 18L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 3L,
                            IdPrestadorEspecialidad = 18L
                        },
                        new
                        {
                            Id = 19L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 3L,
                            IdPrestadorEspecialidad = 19L
                        },
                        new
                        {
                            Id = 20L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 3L,
                            IdPrestadorEspecialidad = 20L
                        },
                        new
                        {
                            Id = 21L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 3L,
                            IdPrestadorEspecialidad = 21L
                        },
                        new
                        {
                            Id = 22L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 3L,
                            IdPrestadorEspecialidad = 22L
                        },
                        new
                        {
                            Id = 23L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 3L,
                            IdPrestadorEspecialidad = 23L
                        },
                        new
                        {
                            Id = 24L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 3L,
                            IdPrestadorEspecialidad = 24L
                        },
                        new
                        {
                            Id = 25L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 2L,
                            IdPrestadorEspecialidad = 25L
                        },
                        new
                        {
                            Id = 26L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 2L,
                            IdPrestadorEspecialidad = 26L
                        },
                        new
                        {
                            Id = 27L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 2L,
                            IdPrestadorEspecialidad = 27L
                        },
                        new
                        {
                            Id = 28L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 2L,
                            IdPrestadorEspecialidad = 28L
                        },
                        new
                        {
                            Id = 29L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 2L,
                            IdPrestadorEspecialidad = 29L
                        },
                        new
                        {
                            Id = 30L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 2L,
                            IdPrestadorEspecialidad = 30L
                        },
                        new
                        {
                            Id = 31L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 2L,
                            IdPrestadorEspecialidad = 31L
                        },
                        new
                        {
                            Id = 32L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 2L,
                            IdPrestadorEspecialidad = 32L
                        },
                        new
                        {
                            Id = 33L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 2L,
                            IdPrestadorEspecialidad = 33L
                        },
                        new
                        {
                            Id = 34L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 2L,
                            IdPrestadorEspecialidad = 34L
                        },
                        new
                        {
                            Id = 35L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 2L,
                            IdPrestadorEspecialidad = 35L
                        },
                        new
                        {
                            Id = 36L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 2L,
                            IdPrestadorEspecialidad = 36L
                        },
                        new
                        {
                            Id = 37L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 2L,
                            IdPrestadorEspecialidad = 37L
                        },
                        new
                        {
                            Id = 38L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 1L,
                            IdPrestadorEspecialidad = 38L
                        },
                        new
                        {
                            Id = 39L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 1L,
                            IdPrestadorEspecialidad = 39L
                        },
                        new
                        {
                            Id = 40L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 1L,
                            IdPrestadorEspecialidad = 40L
                        },
                        new
                        {
                            Id = 41L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 1L,
                            IdPrestadorEspecialidad = 41L
                        },
                        new
                        {
                            Id = 42L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 1L,
                            IdPrestadorEspecialidad = 42L
                        },
                        new
                        {
                            Id = 43L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 1L,
                            IdPrestadorEspecialidad = 43L
                        },
                        new
                        {
                            Id = 44L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 1L,
                            IdPrestadorEspecialidad = 44L
                        },
                        new
                        {
                            Id = 45L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 1L,
                            IdPrestadorEspecialidad = 45L
                        },
                        new
                        {
                            Id = 46L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 1L,
                            IdPrestadorEspecialidad = 46L
                        },
                        new
                        {
                            Id = 47L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 1L,
                            IdPrestadorEspecialidad = 47L
                        },
                        new
                        {
                            Id = 48L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 1L,
                            IdPrestadorEspecialidad = 48L
                        },
                        new
                        {
                            Id = 49L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 1L,
                            IdPrestadorEspecialidad = 49L
                        },
                        new
                        {
                            Id = 50L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 1L,
                            IdPrestadorEspecialidad = 50L
                        },
                        new
                        {
                            Id = 51L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 1L,
                            IdPrestadorEspecialidad = 51L
                        },
                        new
                        {
                            Id = 52L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 1L,
                            IdPrestadorEspecialidad = 52L
                        },
                        new
                        {
                            Id = 53L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 1L,
                            IdPrestadorEspecialidad = 53L
                        },
                        new
                        {
                            Id = 54L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 1L,
                            IdPrestadorEspecialidad = 54L
                        },
                        new
                        {
                            Id = 55L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 1L,
                            IdPrestadorEspecialidad = 55L
                        },
                        new
                        {
                            Id = 56L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 1L,
                            IdPrestadorEspecialidad = 57L
                        },
                        new
                        {
                            Id = 57L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 1L,
                            IdPrestadorEspecialidad = 57L
                        },
                        new
                        {
                            Id = 58L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 1L,
                            IdPrestadorEspecialidad = 58L
                        },
                        new
                        {
                            Id = 59L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 1L,
                            IdPrestadorEspecialidad = 59L
                        },
                        new
                        {
                            Id = 60L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 1L,
                            IdPrestadorEspecialidad = 60L
                        },
                        new
                        {
                            Id = 61L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 4L,
                            IdPrestadorEspecialidad = 61L
                        },
                        new
                        {
                            Id = 62L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 4L,
                            IdPrestadorEspecialidad = 62L
                        },
                        new
                        {
                            Id = 63L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 4L,
                            IdPrestadorEspecialidad = 63L
                        },
                        new
                        {
                            Id = 64L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 4L,
                            IdPrestadorEspecialidad = 64L
                        },
                        new
                        {
                            Id = 65L,
                            EstaEliminado = (short)0,
                            IdEstablecimiento = 4L,
                            IdPrestadorEspecialidad = 65L
                        });
                });

            modelBuilder.Entity("Galenort.Dominio.Entidades.DiaHorario", b =>
                {
                    b.HasOne("Galenort.Dominio.Entidades.Dia", "Dia")
                        .WithMany("DiaHorarios")
                        .HasForeignKey("IdDia")
                        .HasConstraintName("FK_Dia_DiaHorarios")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Galenort.Dominio.Entidades.HorarioPrestador", "HorarioPrestador")
                        .WithMany("DiaHorarios")
                        .HasForeignKey("IdHorarioPrestador")
                        .HasConstraintName("FK_HorarioPrestador_DiaHorarios")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Galenort.Dominio.Entidades.Establecimiento", b =>
                {
                    b.HasOne("Galenort.Dominio.Entidades.Localidad", "Localidad")
                        .WithMany("Establecimientos")
                        .HasForeignKey("IdLocalidad")
                        .HasConstraintName("FK_Localidad_Establecimientos")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Galenort.Dominio.Entidades.HorarioPrestador", b =>
                {
                    b.HasOne("Galenort.Dominio.Entidades.PrestadorEstablecimiento", "PrestadorEstablecimiento")
                        .WithMany("HorarioPrestadores")
                        .HasForeignKey("IdPrestadorEstablecimiento")
                        .HasConstraintName("FK_PrestadorEstablecimiento_HorarioPrestadores")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Galenort.Dominio.Entidades.PrestadorEspecialidad", b =>
                {
                    b.HasOne("Galenort.Dominio.Entidades.Especialidad", "Especialidad")
                        .WithMany("PrestadorEspecialidades")
                        .HasForeignKey("IdEspecialidad")
                        .HasConstraintName("FK_Especialidad_PrestadorEspecialidad")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Galenort.Dominio.Entidades.Prestador", "Prestador")
                        .WithMany("PrestadorEspecialidades")
                        .HasForeignKey("IdPrestador")
                        .HasConstraintName("FK_Prestador_PrestadorEspecialidad")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Galenort.Dominio.Entidades.PrestadorEstablecimiento", b =>
                {
                    b.HasOne("Galenort.Dominio.Entidades.Establecimiento", "Establecimiento")
                        .WithMany("PrestadorEstablecimientos")
                        .HasForeignKey("IdEstablecimiento")
                        .HasConstraintName("FK_Establecimiento_PrestadorEstablecimientos")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Galenort.Dominio.Entidades.PrestadorEspecialidad", "PrestadorEspecialidad")
                        .WithMany("PrestadorEstablecimientos")
                        .HasForeignKey("IdPrestadorEspecialidad")
                        .HasConstraintName("FK_Prestador_PrestadorEstablecimientos")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
